-- ============================================================
-- TENNIS POINT — Bulk de usuários do Torneio 2026
-- Roda este script INTEIRO no SQL Editor do Supabase (admin context).
-- Senha de todos: tennis123
-- Total: 153 contas
-- Idempotente: ON CONFLICT (email) DO NOTHING
-- ============================================================

CREATE EXTENSION IF NOT EXISTS pgcrypto;

BEGIN;

WITH new_users(email, full_name) AS (
  VALUES
  ('alanr@tennispointt.com.br', 'Alan R.'),
  ('aldecir@tennispointt.com.br', 'Aldecir'),
  ('alexjapa@tennispointt.com.br', 'Alex Japa'),
  ('alvaro@tennispointt.com.br', 'Alvaro'),
  ('andrer@tennispointt.com.br', 'André R.'),
  ('aperu@tennispointt.com.br', 'A. Peru'),
  ('arentes@tennispointt.com.br', 'A. Rentes'),
  ('arthur@tennispointt.com.br', 'Arthur'),
  ('augusto@tennispointt.com.br', 'Augusto'),
  ('baduca@tennispointt.com.br', 'Baduca'),
  ('breno@tennispointt.com.br', 'Breno'),
  ('brunnoc@tennispointt.com.br', 'Brunno C.'),
  ('brunodiniz@tennispointt.com.br', 'Bruno Diniz'),
  ('brunoo@tennispointt.com.br', 'Bruno O.'),
  ('brunooliv@tennispointt.com.br', 'Bruno Oliv.'),
  ('brunop@tennispointt.com.br', 'Bruno P.'),
  ('brunopozzatti@tennispointt.com.br', 'Bruno Pozzatti'),
  ('bueno@tennispointt.com.br', 'Bueno'),
  ('caio@tennispointt.com.br', 'Caio'),
  ('celio@tennispointt.com.br', 'Célio'),
  ('china@tennispointt.com.br', 'China'),
  ('claudinho@tennispointt.com.br', 'Claudinho'),
  ('cleiton@tennispointt.com.br', 'Cleiton'),
  ('cristian@tennispointt.com.br', 'Cristian'),
  ('cristianolodi@tennispointt.com.br', 'Cristiano Lodi'),
  ('cristianub@tennispointt.com.br', 'Cristian Ub.'),
  ('danilo@tennispointt.com.br', 'Danilo'),
  ('drdouglas@tennispointt.com.br', 'Dr Douglas'),
  ('duarte@tennispointt.com.br', 'Duarte'),
  ('eden@tennispointt.com.br', 'Éden'),
  ('edmilson@tennispointt.com.br', 'Edmilson'),
  ('educap@tennispointt.com.br', 'Edu Cap.'),
  ('elaine@tennispointt.com.br', 'Elaine'),
  ('fabinho@tennispointt.com.br', 'Fabinho'),
  ('fabioi@tennispointt.com.br', 'Fábio I.'),
  ('fagner@tennispointt.com.br', 'Fagner'),
  ('fcarvoli@tennispointt.com.br', 'F. Carvoli'),
  ('felipec@tennispointt.com.br', 'Felipe C.'),
  ('fernandorufino@tennispointt.com.br', 'Fernando Rufino'),
  ('fernandosseb@tennispointt.com.br', 'Fernando S. Seb.'),
  ('flavio@tennispointt.com.br', 'Flávio'),
  ('flaviom@tennispointt.com.br', 'Flávio M.'),
  ('fredi@tennispointt.com.br', 'Fredi'),
  ('gabrielub@tennispointt.com.br', 'Gabriel Ub.'),
  ('gianni@tennispointt.com.br', 'Gianni'),
  ('giovani@tennispointt.com.br', 'Giovani'),
  ('glaucobeach@tennispointt.com.br', 'Glauco Beach'),
  ('guilherme@tennispointt.com.br', 'Guilherme'),
  ('guilhermeub@tennispointt.com.br', 'Guilherme Ub.'),
  ('guilhermo@tennispointt.com.br', 'Guilhermo'),
  ('gustavosc@tennispointt.com.br', 'Gustavo sc'),
  ('guto@tennispointt.com.br', 'Guto'),
  ('henrique@tennispointt.com.br', 'Henrique'),
  ('heraldo@tennispointt.com.br', 'Heraldo'),
  ('humberto@tennispointt.com.br', 'Humberto'),
  ('ian@tennispointt.com.br', 'Ian'),
  ('igor@tennispointt.com.br', 'Igor'),
  ('jaco@tennispointt.com.br', 'Jaco'),
  ('joaocurti@tennispointt.com.br', 'João Curti'),
  ('joaog@tennispointt.com.br', 'João G.'),
  ('joaogoulart@tennispointt.com.br', 'João Goulart'),
  ('joaoguilherme@tennispointt.com.br', 'João Guilherme'),
  ('joaorj@tennispointt.com.br', 'João RJ'),
  ('joaorossi@tennispointt.com.br', 'João Rossi'),
  ('joaov@tennispointt.com.br', 'João V.'),
  ('johnatan@tennispointt.com.br', 'Johnatan'),
  ('jorgi@tennispointt.com.br', 'Jorgi'),
  ('juliano@tennispointt.com.br', 'Juliano'),
  ('julioguto@tennispointt.com.br', 'Júlio Guto'),
  ('juliop@tennispointt.com.br', 'Júlio P.'),
  ('juscelino@tennispointt.com.br', 'Juscelino'),
  ('lcastro@tennispointt.com.br', 'L. Castro'),
  ('leandroneves@tennispointt.com.br', 'Leandro Neves'),
  ('leocurti@tennispointt.com.br', 'Léo Curti'),
  ('leopaes@tennispointt.com.br', 'Léo Paes'),
  ('lfelipe@tennispointt.com.br', 'L. Felipe'),
  ('longueti@tennispointt.com.br', 'Longueti'),
  ('lrebolcas@tennispointt.com.br', 'L. Rebolças'),
  ('lucasb@tennispointt.com.br', 'Lucas B.'),
  ('lucasbur@tennispointt.com.br', 'Lucas Bur.'),
  ('lucascastro@tennispointt.com.br', 'Lucas Castro'),
  ('lucasgallina@tennispointt.com.br', 'Lucas Gallina'),
  ('lucasn@tennispointt.com.br', 'Lucas N.'),
  ('lucasramos@tennispointt.com.br', 'Lucas Ramos'),
  ('lucianoub@tennispointt.com.br', 'Luciano Ub.'),
  ('luise@tennispointt.com.br', 'Luís E.'),
  ('luiseduardo@tennispointt.com.br', 'Luis Eduardo'),
  ('luisfelipe@tennispointt.com.br', 'Luis Felipe'),
  ('lukas@tennispointt.com.br', 'Lukas'),
  ('magal@tennispointt.com.br', 'Magal'),
  ('magno@tennispointt.com.br', 'Magno'),
  ('marcaoh@tennispointt.com.br', 'Marcão H.'),
  ('marcelinho@tennispointt.com.br', 'Marcelinho'),
  ('marcelor@tennispointt.com.br', 'Marcelo R.'),
  ('marceloribeiro@tennispointt.com.br', 'Marcelo Ribeiro'),
  ('marcoq@tennispointt.com.br', 'Marco Q.'),
  ('mariochile@tennispointt.com.br', 'Mário Chile'),
  ('martin@tennispointt.com.br', 'Martin'),
  ('mbomba@tennispointt.com.br', 'M. Bomba'),
  ('mcaldera@tennispointt.com.br', 'M. Caldera'),
  ('mcanete@tennispointt.com.br', 'M. Canete'),
  ('miro@tennispointt.com.br', 'Miro'),
  ('nicolas@tennispointt.com.br', 'Nícolas'),
  ('pan@tennispointt.com.br', 'Pan'),
  ('panda@tennispointt.com.br', 'Panda'),
  ('paulao@tennispointt.com.br', 'Paulão'),
  ('paulo@tennispointt.com.br', 'Paulo'),
  ('pedrohenrique@tennispointt.com.br', 'Pedro Henrique'),
  ('pedrokokol@tennispointt.com.br', 'Pedro Kokol'),
  ('pepe@tennispointt.com.br', 'Pepe'),
  ('peru@tennispointt.com.br', 'Peru'),
  ('quina@tennispointt.com.br', 'Quina'),
  ('rafaele@tennispointt.com.br', 'Rafael E.'),
  ('rafaelgim@tennispointt.com.br', 'Rafael Gim.'),
  ('rafaelk@tennispointt.com.br', 'Rafael K.'),
  ('ratinho@tennispointt.com.br', 'Ratinho'),
  ('rbarros@tennispointt.com.br', 'R. Barros'),
  ('reinaldo@tennispointt.com.br', 'Reinaldo'),
  ('renan@tennispointt.com.br', 'Renan'),
  ('rgimenes@tennispointt.com.br', 'R. Gimenes'),
  ('riad@tennispointt.com.br', 'Riad'),
  ('robertinho@tennispointt.com.br', 'Robertinho'),
  ('rodrigobarros@tennispointt.com.br', 'Rodrigo Barros'),
  ('rodrigoquina@tennispointt.com.br', 'Rodrigo Quina'),
  ('rodrigorib@tennispointt.com.br', 'Rodrigo Rib.'),
  ('rodrigoub@tennispointt.com.br', 'Rodrigo Ub.'),
  ('rodrigov@tennispointt.com.br', 'Rodrigo V.'),
  ('rogerio@tennispointt.com.br', 'Rogério'),
  ('rogester@tennispointt.com.br', 'Rogester'),
  ('romeu@tennispointt.com.br', 'Romeu'),
  ('rsetor@tennispointt.com.br', 'R. Setor'),
  ('salomao@tennispointt.com.br', 'Salomão'),
  ('sandro@tennispointt.com.br', 'Sandro'),
  ('serginho@tennispointt.com.br', 'Serginho'),
  ('sharles@tennispointt.com.br', 'Sharles'),
  ('silvio@tennispointt.com.br', 'Sílvio'),
  ('tammaro@tennispointt.com.br', 'Tammaro'),
  ('tbispo@tennispointt.com.br', 'T. Bispo'),
  ('thais@tennispointt.com.br', 'Thais'),
  ('thiagoc@tennispointt.com.br', 'Thiago C.'),
  ('thiagocosta@tennispointt.com.br', 'Thiago Costa'),
  ('thiaguinho@tennispointt.com.br', 'Thiaguinho'),
  ('tiagobispo@tennispointt.com.br', 'Tiago Bispo'),
  ('tiagoburihan@tennispointt.com.br', 'Tiago Burihan'),
  ('titis@tennispointt.com.br', 'Titis'),
  ('ton@tennispointt.com.br', 'Ton'),
  ('ulisses@tennispointt.com.br', 'Ulisses'),
  ('vinicius@tennispointt.com.br', 'Vinícius'),
  ('vitor@tennispointt.com.br', 'Vitor'),
  ('wando@tennispointt.com.br', 'Wando'),
  ('wilson@tennispointt.com.br', 'Wilson'),
  ('yan@tennispointt.com.br', 'Yan'),
  ('zuca@tennispointt.com.br', 'Zuca')
)
INSERT INTO auth.users (
  instance_id, id, aud, role, email, encrypted_password,
  email_confirmed_at, raw_app_meta_data, raw_user_meta_data,
  created_at, updated_at,
  confirmation_token, email_change, email_change_token_new, recovery_token
)
SELECT
  '00000000-0000-0000-0000-000000000000'::uuid,
  gen_random_uuid(),
  'authenticated',
  'authenticated',
  nu.email,
  crypt('tennis123', gen_salt('bf')),
  now(),
  '{"provider":"email","providers":["email"]}'::jsonb,
  jsonb_build_object('name', nu.full_name, 'source', 'tp2026-bulk'),
  now(),
  now(),
  '', '', '', ''
FROM new_users nu
ON CONFLICT (email) DO NOTHING;

COMMIT;

-- ============================================================
-- Verificação (rode DEPOIS):
-- SELECT count(*) FROM auth.users WHERE email LIKE '%@tennispointt.com.br';
-- SELECT email, email_confirmed_at IS NOT NULL AS confirmed FROM auth.users WHERE email LIKE '%@tennispointt.com.br' ORDER BY email LIMIT 20;
-- ============================================================
